const Sequelize=require('sequelize')
const seq=require('../sequelize')
const RecommendsBooks=seq.define('recommendBooks',{
    title:{
        type:Sequelize.TEXT,
        allowNull:false
    },
    imgSrc:{
        type:Sequelize.STRING,
        allowNull:true
    },
    price:{
        type:Sequelize.STRING,
        allowNull:false
    },
    author:{
        type:Sequelize.STRING,
        allowNull:true
    },
    publicStore:{
        type:Sequelize.STRING,
        allowNull:true
    },
    work:{
        type:Sequelize.STRING,
        allowNull:true
    },
    fixPrice:{
        type:Sequelize.STRING,
        allowNull:true
    },
    desc:{
        type:Sequelize.TEXT,
        allowNull:true
    },
    e_price:{
        type:Sequelize.TEXT,
        allowNull:true
    },
    publicTime:{
        type:Sequelize.STRING,
        allowNull:true
    },
    discount:{
        type:Sequelize.STRING,
        allowNull:true
    }
})
module.exports=RecommendsBooks
